Resource pool sessions handling regression with login state
eclipse-keypont/crypto11 pull request #10
Opened 2018-09-04 17:24 UTC by sitano

### Abstract

Resource pool handles sessions which require a login procedure wrong.

### Issue: https://github.com/ThalesIgnite/crypto11/issues/9

### Description

If it is easy to fix logging issue for new sessions in the pool, I am not sure it will be easy to do anything for rancid handles.

One of the consequences of using resource pool with expiration is that users handles got rancid when related session got kicked out of the pool, and thus it becomes impossible to store any handles kinds cross the requests boundaries for loaded services. Another way of handling it could be to force them to implement some routine of handling this specific error `CKR_OBJECT_HANDLE_INVALID`. From the point of view of this change caused by an introduction of RP https://github.com/ThalesIgnite/crypto11/pull/3 backward compatibility is broken.

### Mitigation plan

- test which reproduces regressions (handling of `pkcs11: 0x101: CKR_USER_NOT_LOGGED_IN`).
- check handling of handles from previous sessions with `pkcs11: 0x82: CKR_OBJECT_HANDLE_INVALID`.
- make idle timeout configurable, reduce idle timeout in test.
- fix sessions handling

### Backward compatibility

- IdleTimeout exposed to the configuration
- IdleTimeout is 0 by default
- NewSessionTimeout is 0 by default and replaced with the PoolTimeout to the configuration

2018-09-10 13:51 UTC, sitano commented
@optnfast done

2018-09-14 09:55 UTC, sitano commented
@cbroglie I've made IdleTimeout and PoolTimeout to the lib config. But having MaxSessions = 1024 by default would allow 1024 non evictable sessions with the IdleTimeout = 0 by default. I am not sure it's good allowing such almost unbound resource usage. But I don't know whats the best option here.

2018-09-15 01:49 UTC, cbroglie commented
Thanks, I updated our code to use your latest changes in https://github.com/cloudflare/gokeyless/pull/246, and it seems to be working as expected.

2018-09-24 11:24 UTC, nickrmc83 requested changes
There's a single comment to be addressed but otherwise the PR looks good. Once the change, or counter argument to the change, has been made we'll approve.

2018-09-24 11:24 UTC, nickrmc83 commented on sessions.go
> +			code == pkcs11.CKR_USER_ANOTHER_ALREADY_LOGGED_IN ||
CKR_USER_ANOTHER_ALREADY_LOGGED_IN should be treated as an error as it indicates another user is logged in, not the user configured.

2018-09-25 09:56 UTC, sitano commented on sessions.go
> +			code == pkcs11.CKR_USER_ANOTHER_ALREADY_LOGGED_IN ||
Done.

2018-09-25 11:41 UTC, nickrmc83 approved these changes

2018-09-25 12:01 UTC, merged

2018-09-25 12:02 UTC, nickrmc83 commented
@sitano Thanks for the PR!