Improve session handling
eclipse-keypont/crypto11 pull request #3
Opened 2018-06-19 19:03 UTC by cbroglie

This adds the following functionality:
- Make the maximum number of sessions configurable
- Ensure we never open more sessions than the max we specify
- Timeout instead of (potentially) blocking forever waiting on a session
- Close idle sessions

These changes were tested using SoftHSM2.

2018-06-19 21:19 UTC, mahrud requested changes
Also works with YubiKey when `MaxSessions=1`.

2018-06-19 21:19 UTC, mahrud commented on dsa.go
> +	pubHandle, privHandle, err := libHandle.GenerateKeyPair(session.Handle,
Is there a logic behind passing `PKCS11Session` to some functions and `SessionHandle` to others?

2018-06-19 21:19 UTC, mahrud commented on ecdsa.go
> +	if attributes, err = libHandle.GetAttributeValue(session.Handle, pubHandle, template); err != nil {
Adding to the previous comment, I think having two different "handles" (one `libHandle` and one `session.Handle`) is a little confusing.

2018-06-19 21:19 UTC, mahrud commented on sessions.go
> -	defer sessionPoolMutex.Unlock()
Is there a benefit to putting this in the end?

2018-06-19 21:19 UTC, mahrud commented on crypto11.go
> +		return nil, fmt.Errorf("crypto11: provided max sessions value (%d) exceeds max value the token supports (%d)", maxSessions, token.MaxRwSessionCount)
Use `log.Fatalf` instead since `log` is already imported.

2018-06-19 21:19 UTC, mahrud commented on sessions.go
> +	defer cancel()
Is there a probability that this would cut off a session that is active?

2018-06-19 21:53 UTC, cbroglie commented on dsa.go
> +	pubHandle, privHandle, err := libHandle.GenerateKeyPair(session.Handle,
All of the functions in crypto11 should operate on `*PKCS11Session`, whereas all of the functions in pkcs11 accept a `pkcs11.SessionHandle`.

2018-06-19 21:55 UTC, cbroglie commented on ecdsa.go
> +	if attributes, err = libHandle.GetAttributeValue(session.Handle, pubHandle, template); err != nil {
That's the nature of pkcs11 - there are many handles. I'm just maintaining the existing conventions, see `PKCS11Object` for another example:
```go
// PKCS11Object contains a reference to a loaded PKCS#11 object.
type PKCS11Object struct {
	// The PKCS#11 object handle.
	Handle pkcs11.ObjectHandle

	// The PKCS#11 slot number.
	//
	// This is used internally to find a session handle that can
	// access this object.
	Slot uint
}
```

2018-06-19 21:56 UTC, cbroglie commented on sessions.go
> -	defer sessionPoolMutex.Unlock()
There is a very minor (negligible here) performance impact of using `defer`, so for simple functions without any early returns I've developed the habit of not using it.

2018-06-19 21:58 UTC, cbroglie commented on crypto11.go
> +		return nil, fmt.Errorf("crypto11: provided max sessions value (%d) exceeds max value the token supports (%d)", maxSessions, token.MaxRwSessionCount)
I'm merely returning an error here, not trying to make the application exit (which is what `log.Fatal` will do). Handling the error is up to the calling application.

2018-06-19 21:59 UTC, cbroglie commented on sessions.go
> +	defer cancel()
Good question, but no, the context is only used as a timeout inside `Get`.

2018-06-21 07:41 UTC, mahrud commented
Confirmed that also works with the Thales nShield HSM.

2018-06-21 17:37 UTC, mahrud commented on crypto11.go
> +		return nil, fmt.Errorf("crypto11: provided max sessions value (%d) exceeds max value the token supports (%d)", maxSessions, token.MaxRwSessionCount)
I understand, but if you look above, this same function is logging errors in addition to returning errors. I think it's a good idea given that this function handles hardware. What do you think?

2018-06-21 17:38 UTC, mahrud commented on sessions.go
> +	defer cancel()
Would still like to test this in practice when we can.

2018-06-25 09:33 UTC, nfewx commented on crypto11.go
> +		return nil, fmt.Errorf("crypto11: provided max sessions value (%d) exceeds max value the token supports (%d)", maxSessions, token.MaxRwSessionCount)
Current behavior (i.e.without this PR) is a bit inconsistent; I've created https://github.com/ThalesIgnite/crypto11/issues/4 as a placeholder for doing a cleanup at some later date.

2018-06-25 10:48 UTC, merged

2018-06-25 10:53 UTC, nfewx commented
Thanks for the PR!